### ISSUE TITLE
[Bug]: Rolldown cannot treeshake unused branch

### ISSUE THREAD

**Issue by ocavue** [rolldown/rolldown#4258]
### Reproduction link or steps

https://github.com/issueset/test-rolldown-rollup-treeshake

### What is expected?

The unused branch get removed, like Rollup's output:

```js
// dist/output_rollup/main.js

const bar = "BAR";

function main() {

  console.log(bar);
}

export { main };
```

### What is actually happening?

The unused branch still exists:

```js
// dist/output_rolldown/main.js

//#region src/bar.js
const bar = "BAR";

//#endregion
//#region src/foo.js
const foo = false;
var foo_default = foo;

//#endregion
//#region src/main.js
function main() {
	if (foo_default) console.warn("I expected this warning to be removed in the final bundle.");
	console.log(bar);
}

//#endregion
export { main };
```

### System Info

```Shell
System:
    OS: macOS 15.3.1
    CPU: (8) arm64 Apple M2
    Memory: 3.25 GB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.18.1 - /opt/homebrew/opt/node@20/bin/node
    Yarn: 1.22.22 - /opt/homebrew/opt/node@20/bin/yarn
    npm: 10.8.2 - /opt/homebrew/opt/node@20/bin/npm
    pnpm: 10.8.1 - /opt/homebrew/bin/pnpm
    bun: 1.2.9 - /opt/homebrew/bin/bun
  Browsers:
    Brave Browser: 122.1.63.169
    Chrome: 135.0.7049.96
    Chrome Canary: 137.0.7138.0
    Safari: 18.3
    Safari Technology Preview: 18.2
  npmPackages:
    rolldown: 1.0.0-beta.8 => 1.0.0-beta.8
```

### Any additional comments?

I can find similar unoptimized behavior from ESBuild (https://github.com/evanw/esbuild/issues/4148).

**Comment by IWANABETHATGUY** [comment]
This is the limitation of the current analyzer(which is similar to esbuild), it only analyzes top-level stmt, and will not try to inline const variables and eliminate statements that are not top-level.

**Comment by IWANABETHATGUY** [comment]
But if you don't need readable output, just enable `output.minify`; this issue should be resolved.

**Comment by yyx990803** [comment]
Whether "Treeshaking" or dead-code elimination should be handled by the bundler or the minifier is actually a blurry line.

Rollup performs some advanced treeshaking because it does not have a built-in minifier and cannot assume how users will optimize bundled code further. For Rolldown, however, this kind of optimization is handled by the built-in minifier. If you care about bundle size your probably want to enable minification as well.

Rollup-like optimization for this only serves the rare case where you don't want minification but still want smaller bundles, which is why this is considered low priority. Maybe an alternative would be offer a minifier preset where it only performs DCE but no mangling / whitespace removal?

**Comment by IWANABETHATGUY** [comment]
There exists  `output.minify: 'dce-only'` already,  but `oxc-monifier` did not support inline for now, so the **dead branch** inside the function body is still preserved even set `output.minify: 'dce-only'`

**Comment by ocavue** [comment]
> just enable `output.minify`; this issue should be resolved.



I added `output.minify: true` but it seems the dead branch still exists.

```
// dist/output_rolldown/main.js
const e=`BAR`,t=!1;var n=t;function r(){n&&console.warn(`I expected this warning to be removed in the final bundle.`),console.log(e)}export{r as main};
```

**Comment by ocavue** [comment]
I first saw this issue in my Svelte project, where `vite-rolldown` has a larger bundle size output compared to `vite`. Here is the reproduction:

-  Git repo: https://github.com/issueset/test-vite-rolldown-svelte/
-  `vite` output (18K): https://raw.githubusercontent.com/issueset/test-vite-rolldown-svelte/refs/heads/master/dist/output_vite/assets/index-BJufP5Ak.js
-  `vite-rolldown` output (32K): https://raw.githubusercontent.com/issueset/test-vite-rolldown-svelte/refs/heads/master/dist/output_vite_rolldown/assets/index-DyXdjb-i.js

Notice the following part between these two outputs:

```js
// dist/output_vite/assets/index-BJufP5Ak.js
function pe() {
  throw new Error("https://svelte.dev/e/state_unsafe_mutation");
}
```

```js
// dist/output_vite_rolldown/assets/index-DyXdjb-i.js
var a = !1
// ... 
function De() {
  if (a) {
    let e = Error(`state_unsafe_mutation
Updating state inside a derived or a template expression is forbidden. If the value should not be reactive, declare it without \`$state\`
https://svelte.dev/e/state_unsafe_mutation`);
    throw ((e.name = `Svelte error`), e);
  } else throw Error(`https://svelte.dev/e/state_unsafe_mutation`);
}
```

You can find the source code in the Svelte repo for this function [here](https://github.com/sveltejs/svelte/blob/1c2fc210232c16d2eb0fdb20d9bac3cef2b87897/packages/svelte/src/internal/client/errors.js#L313-L322).

For final users, it would be good if `vite-rolldown` could eliminate such dead branches in the production output like what `vite` does, no matter whether it's done in the tree-shaking or minification steps.

**Comment by yyx990803** [comment]
Sorry, looking at this, it should be considered a legit bug.

Also adjusted the priority.

**Comment by IWANABETHATGUY** [comment]
It is due to const inline(which could be handled by minifier) and unused side effects free class elimination, this is a feature that even the minifier(has best compress ratio) did not support, Although this has a high priority but it may require some time to investigate how to implement it  properly.
### Swc
https://play.swc.rs/?version=1.11.22&code=H4sIAAAAAAAAAz2OSw7CMAxE18kpZtluuABixRV6gWDMR1i21LhCCPXujYOoJW88b2ZMUmrFhG9OZFp9XshtHsZ2yGltW%2BpHCU1TJufruYhcCr06kZJz9WE8Bgo8WMS6gDYRZ8IHsXsQwJpbXr4tSv40xc%2F6L97JgPonKDhB%2BY0p7BtTG91qqAAAAA%3D%3D&config=H4sIAAAAAAAAA51VzW7bMAy%2B7ykKn4u162EYet3Q2057AEOxKIedJBoilTYo%2Bu6jHTtNGjqH3Wx%2B%2FPhP6u3LzU3zzF3zePOmn%2FozuMJQjv8q4X0W96qSRvYDcFdwkOZ2QYVHSEqFSfJ%2BABpxpQcZScAP9w%2F3zSIvLnOgkk49VIZfEDDDE5Wf0TE%2FIUTPs92jqwKukxOeijANVOQP1dLB6GwrMvDj3R1w%2Bsrbu%2BFAuf0glJoF06TrqlBygl0zw%2B9nGUQiHvWCizzH0CTMGPanoXeU1AnzeViafE2Qhc%2F5M1bo5XNuKt8QRdDirCOt4xazQA%2FFMtxRjG5gaHeuGFbGSF1BJsvFCFYB3w6FBhPPHgUpq89L1IPzbUceDAgLdII7sGjqS2mZNT0jnwn2sKl9Pw3kJzbsXKxODJ%2FwOrVEozWsbglZ2lCzVcIDuFKDAzgX9zMTQ1tAasmXvGfCvNKTvwBagXHis0tg2Z00gs7TGjtcZWLWtULZG7jOt5Vlhl6L2iIGo7JjZaAIWt0s4GsHY2U7K5wZXikfo4cWQtBZMUzzC0q3tZyOF4mCAWh%2FXbCm6gC0xy1cwceFuAI%2FaZZiD9isoZdlu47yPm0oXnGQQLbkryhoK4TW4aJX4nVYx2v208X1pooeZG8eAV0AoTZOl%2F1iNnQ91GLbR9qYZ2LQOZ%2Ba%2BLAc3ONpTy730xE4OaJCQ4QdxP9fm6uoxrsbJ33Z9ouNhh%2FWoDpdRvx2v0DnT8eXOacmka8n%2BUxzengMvzcfSstrsqTXIP9eiNOL%2Bv4PVrQXxqAHAAA%3D


### Rollup
https://rollupjs.org/repl/?version=2.59.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyY2xhc3MlMjBUJTIwJTdCJTVDbiU1Q3Rjb25zdHJ1Y3RvcigpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCU1Q24lNUN0JTdEJTVDbiU1Q24lNUN0YXN5bmMlMjBjb25uZWN0ZWRDYWxsYmFjaygpJTIwJTdCJTVDbiU1Q3QlNUN0dGVzdCgpJTNCJTVDbiU1Q3QlN0QlNUNuJTIwJTIwaGVsbG8oKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBjb25zb2xlLmxvZygpJTNCJTVDbiUyMCUyMCU3RCU1Q24lN0QlNUNuJTVDbiU1Q25mdW5jdGlvbiUyMHRlc3QoKSUyMCU3QiU1Q24lNUN0Y29uc29sZS5sb2coKSU1Q24lN0QlNUNuJTVDbmNvbnN0JTIwYSUyMCUzRCUyMG5ldyUyMFQoKSUzQiU1Q24lMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJkZXAuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyY29uc29sZS5sb2coJ2RlcCcpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiU3RCU3RA==

**Comment by mary-ext** [comment]
here's an example I have involving dozens of codegen'd schemas, the output contains a considerable amount of remnants that Rolldown didn't purge.

https://stackblitz.com/edit/github-ckndwe2e?file=src%2Fentry.js

vs. Rollup
https://stackblitz.com/edit/rollup-repro-fagdsrgf?file=src%2Fmain.js

**Comment by TheAlexLichter** [comment]
@mary-ext I just filed #4544 for that (as the root cause might be different than in this case)

**Comment by KTibow** [comment]
The SvelteKit folks might've already communicated this, but turning on the minifier doesn't always fix this. What if the condition is a shared resource, and it's used in multiple entry points? oxc-minify can't go across files.

The fix for all of these cases would be to implement something like Rollup's methods that can convert a condition into a boolean:

https://github.com/rollup/rollup/blob/e4082a84063490503a6ee3b4ac74b45be745f111/src/ast/nodes/IfStatement.ts#L128-L130

Edit: here's the example [rollup repl](https://rollupjs.org/repl/?version=4.46.2&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMHNob3VsZF9lbmFibGVfY29kZSUyMCU3RCUyMGZyb20lMjAlNUMlMjIuJTJGcmVzb3VyY2UlNUMlMjIlNUNuaWYlMjAoc2hvdWxkX2VuYWJsZV9jb2RlKSUyMGNvbnNvbGUubG9nKCU1QyUyMkFjdGl2ZSU1QyUyMiklMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSUyQyUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTdEJTJDJTdCJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMHNob3VsZF9lbmFibGVfY29kZSUyMCU3RCUyMGZyb20lMjAlNUMlMjIuJTJGcmVzb3VyY2UlNUMlMjIlNUNuaWYlMjAoc2hvdWxkX2VuYWJsZV9jb2RlKSUyMGNvbnNvbGUubG9nKCU1QyUyMkFjdGl2ZSU1QyUyMiklMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSUyQyUyMm5hbWUlMjIlM0ElMjJtYWluMi5qcyUyMiU3RCUyQyU3QiUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBjb25zdCUyMHNob3VsZF9lbmFibGVfY29kZSUyMCUzRCUyMGZhbHNlJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTJDJTIybmFtZSUyMiUzQSUyMnJlc291cmNlLmpzJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiU3RCU3RA==) and [rolldown repl](https://repl.rolldown.rs/#eNrFkMtqw0AMRX9l0CYJBJd26ZJFv6DQ9UBwbU06MJHMjJw2mPn3yk7cOo99lnrcq6Pbg4OyBySJx+dC0lAQlLPGGmqt/b7lKKY36Yu70GyRqs+A25obNNm4yHtjoXiKmLiLNarQgiXvzPJWsDI1U+KAReDd0sJbLf6AFlZ6C6GU2GFeQ+QQGv6mQped383Y7kwuIOXYopJ+nNfeW/F6b8JcTPKFpYFDBhq1KW8EG9NbypYs4c9o3KCrujAJQCHHmF6ucxsbD8vt3+ovsFnrhHV+6PT/HbSNcVVI+ApZHQ8qCJVgEsi/rAvEJA==) for comparison

**Comment by IWANABETHATGUY** [comment]
Rolldown has support `inlineConst` but does not implement constant propagation for toplevel var yet.

so, for your case, it failed to eliminate the branch.
https://repl.rolldown.rs/#eNptUTFuwzAM/ArBJQkQuLuLDG2nTgUya1FsKlUhU4EtJ2kN/71kJSMtms2n49F3xwkd1hN6bulapUG/Gesb3mKjsDvFPsEEB9vDDK6PHRisHgRWH4PBR8NlxMV4owUstGG65oGRm+QjQ2c9rzcwGQbwDtYyXBBAE3mIgaqL7Xlt8BVETE2iFtK7H0CfPR8hRTgQ9NTFs1CehSVwnm2Aw8itLDC4kZ8DzOrgtjfE41q8KzdLRMI69SPNW+xjCG28cCWTzh9/NXKH+dNN+jyRFLQvY28nDTksZa0W+cqwmkhqRdbU/wS73EEU2Pkvq4/1Uovn4JleVF+DOi7RftKVfltydgzLfpRM+UhLjoKy96LJjvS2O7nb89PeoArz+RZhQVmYFXrsHTgbBoI7FpTGWRadRRFsoiHh/A2AV9Uv

But if you `export` a const literal rather than an identifier, it worked.

https://repl.rolldown.rs/#eNptUTFuwzAM/ArBJQ4QuLuLDG2nTgUya1FsKlUhU4EtJ2kN/71UJcEtms1n3lF3xxkNNjNa7uhWhzF+MzYr3mEbYX/2Q4AZjnqABczge1BYPwisP0aFj4ozxXi/jgWUsWK6JcLEbbCeodeWqy3MigGsgUrIGQG0nkfvqL7qgSuFryBiagN1EN7tCPG35RMED0eCgXp/kZFlmRIYy9rBceJOFijcyuMAS3Sw7nX+VIn3OFskImEThomWHQ7euc5fuRamsadfjdyZ/OkmfJ5JCjpk2ts5hhxLWZsi3yiOJkK0Imuaf4J96sAL7O2Xjj+bUotlZ5leor6B6DhH+0mX++3I6MmV/SiZ0pFKjoyS96xJjuJt93K356eDwihM5yvCjJLwzoNGu5EAFxFehOF0oDHg8g1ewc/D

**Comment by smallmain** [comment]
Thank you for work.

I rely on dead code elimination (tree shaking) to write cross-platform code:

```ts
// _compile-constant.js is created by plugins based on conditions
// in this case, const COCOS = false, const NODE = true
import { COCOS, NODE } from "./_virtual/_compile-constant.js";
import * as ccenv from "cc/env";
import node_os from "os";

function isWechat() {
	if (COCOS) return ccenv.WECHAT;
	if (NODE) return false;
	return typeof wx !== "undefined";
}
```

In Rollup, this will compile to:

```ts
function isWechat() {
	return false;
}
```

If this feature is not available, an error will occur indicating that the cc/env module does not exist.

All places cannot use `await import` because this must be imported synchronously.

Hope to realize as soon as possible.
